---
title: "Prosjektets historikk"
format: html
sidebar: false
number-sections: false
---

**Nordisk institutt for studier av innovasjon, forskning og utdanning (NIFU) har gjennomført halvårlige spørreundersøkelser blant skoler og skoleeiere på oppdrag fra Utdanningsdirektoratet siden 2009. Undersøkelsene er kjent som Utdanningsdirektoratets spørringer.**

NIFU fortsetter dette arbeidet med en rammeavtale for 2021-2025 med Utdanningsdirektoratet.

Temaene for de enkelte undersøkelsene avtales fra gang til gang og skal dekke Utdanningsdirektoratets kunnskapsbehov til enhver tid. Resultatene fra undersøkelsene offentliggjøres i NIFUs ordinære rapportserie og foreligger nedlastbare i PDF-format på Utdanningsdirektoratets og her.

Nåværende prosjektleder for Utdanningsdirektoratets spørringer til Skole-Norge er [Ann Cecilie Bergene](https://www.nifu.no/employees/ann-cecilie-bergene/) ved NIFU. Se også [Tidligere prosjektledere og prosjektmedarbeidere](#tidligere-prosjektledere-og-prosjektmedarbeidere).

## Bakgrunn

Utdanningsdirektoratet har siden 2009 hatt et system for koordinering av spørreundersøkelser om ulike tema i utdanningssektoren. Et tilsvarende system ble innført for barnehagesektoren i 2014. Formålet med disse koordinerte spørringene er å begrense antallet undersøkelser og dermed redusere belastningen på skole og barnehage. Undersøkelsene blir gjennomført to ganger i året for utdanningssektoren og en gang i året for barnehagesektoren.

Spørreundersøkelsene til utdanningssektoren skal primært dekke to formål. Det første formålet er å gjøre en samordning av små og ad-hoc pregede undersøkelser. Videre skal spørringene være en systematisering av undersøkelser knyttet til direktoratets behov for oppfølging av viktige satsingsområder. For utdanningssektoren er målgruppene for undersøkelsene i hovedsak begrenset til skoleeiere (kommune/fylkeskommune) og skoleledere (grunnskole/videregående), men i enkelte tilfeller gjennomføres også undersøkelser blant lærere og opplæringskontor.

NIFU samarbeider med Trøndelag forskning og Utvikling som gjennomfører spørringene til barnehagesektoren. For barnehagesektoren er målgruppene for undersøkelsen barnehagestyrere, kommunale og private barnehageeiere og lokal barnehagemyndighet.

Resultatene fra undersøkelsene i utdanningssektoren offentliggjøres i NIFUs ordinære rapportserie og foreligger nedlastbare i PDF-format på både [Udirs oversikt](https://www.udir.no/tall-og-forskning/publikasjoner/funn-fra-sporsmal-til-skole-norge/) og her.

## Tidligere prosjektledere og prosjektmedarbeidere {#tidligere-prosjektledere-og-prosjektmedarbeidere}

<!-- (skrape alle forfatterne fra tidligere rapporter, og slå de sammen for å finne perioder) -->
