---
title: "Metode"
sidebar: false
format: html
number-sections: false
toc: false
---

# Generell beskrivelse av undersøkelsene

Undersøkelsen har fire målgrupper: skoleledere ved grunnskoler og videregående skoler, og kommuner og fylkeskommuner som skoleeiere. Antall tema som inngår i undersøkelsene varierer fra gang til gang, og noen tema gjentas med jevne mellomrom. Temaene presenteres i hvert sitt kapittel i rapportene. Rapportene er i stor grad deskriptive, med mange tabeller og figurer. Siden vi ikke oppgir desimaler i tabeller og figurer, vil ikke alltid prosentandeler summere seg nøyaktig til 100. Vær oppmerksom på at i enkelte analyser er gruppene små. Vi rapporterer primært på observerte forskjeller som er statistisk signifikante ifølge Pearsons kji-kvadrattest (5-prosentnivå), og vi har valgt å omtale slike forskjeller som «betydelige». Utdanningsdirektoratets spørringer gjennomføres som regel to ganger hvert år. For å redusere belastningen på sektoren er undersøkelsen organisert som en utvalgsundersøkelse. Grunnskolene er delt inn i tre utvalg, mens videregående skoler og kommuner er fordelt på to. Skoleledere i grunnskolen mottar normalt ikke undersøkelsen oftere enn hvert halvannet år, men skoleledere i videregående og skoleeier kommune får undersøkelsen en gang i året. Fylkeskommunene og Oslo som skoleeier for grunnskolen deltar i undersøkelsen hver gang.

Utvalgene er trukket for å sikre geografisk representativitet og at alle skoletyper skal er med i alle utvalg. Grunnskoleutvalgene er trukket tilfeldig til de tre utvalgene, stratifisert etter fylke og skoleslag (rene grunnskole, 1-10. skoler og rene ungdomsskoler). Videregående skoler og kommuner er trukket tilfeldig til to utvalg stratifisert etter fylke. Merk at noen typer skoler på forhånd er tatt ut av populasjonen, og dermed også av utvalget. Dette gjelder 1) skoler for elever med spesielle behov 2) skoler med læreplaner og organisering som skiller seg sterkt fra ordinære skoler, som for eksempel internasjonale skoler, og 3) skoler med svært få elever, det vil si fem eller færre. Det er ved tidligere anledninger forsøkt å invitere slike skoler, men tilbakemeldingene har i de fleste tilfellene vært at spørsmålene i undersøkelsen ikke er relevante.

Som nevnt er dette hovedsakelig en deskriptiv rapport hvor vi undersøker forskjeller mellom respondenter basert på ulike bakgrunnsvariabler eller kjennetegn. Alle spørsmålene krysses med respondentgruppene, som består av skoleleder grunnskole, skoleleder videregående, skoleeier kommune og skoleeier fylkeskommune. Videre undersøkes svarfordelingen til hver respondentgruppe på ulike bakgrunnsvariabler.

Firedelt skoletype er svarfordelingen fordelt på barneskoler, ungdomsskoler, 1--10-skoler og videregående skoler. Femdelt skoletype skiller i tillegg ut barneskoler som kun har 1.-4. trinn, men denne bakgrunnsvariabler rapporteres det sjeldent på fordi gruppen er så liten. Videre har vi grunnskolestørrelse, som deler grunnskolene inn i tre størrelser: under 100 elever, mellom 100 og 299 elever, og over 300 elever. Vi har to bakgrunnsvariabler som gjelder bare for videregående. Type videregående er svarene fordelt på skoler som kun har studieforberedende utdanningsprogram, har både studieforberedende- og yrkesfaglige utdanningsprogram, og skoler som bare har yrkesfaglige utdanningsprogram. Den andre variabelen er videregåendestørrelse, som skiller mellom skoler med under 250 elever, mellom 250 og 599 elever, og over 600 elever. Den siste skolerelaterte variabelen er skolestørrelse. Her deles skolene inn i de minste, de mellomste og de største, basert på de respektive skolestørrelsesvariablene for grunnskoler og videregående. Altså vil gruppen av de minste skolene bestå av grunnskoler med mindre enn 100 elever og videregående skoler med mindre enn 250 elever.

Når det gjelder geografiske kjennetegn har vi for det første landsdel. For å beholde historikken, og unngå for store geografiske områder, har vi valgt å fortsatt ta utgangspunkt i fylkene før regionreformen i 2020. De ulike landsdelene består av følgende tidligere fylker: Oslo-området: Oslo og Akershus, Øst-Norge: Østfold, Hedmark, Oppland, Buskerud, Vestfold og Telemark, Sør- og Vest-Norge: Aust-Agder, Vest-Agder, Rogaland, Hordaland, Sogn og Fjordane og Møre og Romsdal, Midt- og Nord-Norge: Trøndelag, Nordland, Troms og Finnmark.

For det andre undersøkes variasjoner fordelt på fylkene etter regionreformen. For grunnskoler, videregående skoler og kommuner ser vi også på forskjeller mellom kommuner, og skoler i kommuner av ulik størrelse. Kommunene deles inn i tre kategorier: mindre enn 3 000 innbyggere, mellom 3 000 og 9 999 innbyggere, og 10 000 eller flere innbyggere.

Til slutt ser vi på forskjeller mellom kommuner av ulik sentralitet, og på skoler som ligger i kommuner med ulik sentralitet. Sentralitetsindeksen er hentet fra Statistisk sentralbyrå (SSB). Dette er en indeks som klassifiserer kommuner etter tilgangen på arbeidsplasser og servicefunksjoner, hvor høyere verdier indikerer høyere sentralitet. SSB har i utgangspunktet delt kommunene inn i seks intervaller, hvor intervallene ble laget slik at det ikke skulle bli for få innbyggere i en enkelt gruppe. For å presentere mer oversiktlige tabeller og figurer har vi slått sammen intervallene til tre kategorier: mest sentrale, mellomsentrale og minst sentrale.

| Tema                   | Grunnskole | Videregående | Kommune | Fylkeskommune |
|------------------------|------------|--------------|---------|---------------|
| Respondenttype         | X          | X            | X       | X             |
| Skoletype 4-delt       | X          | X            |         |               |
| Skoletype 5-delt       | X          | X            |         |               |
| Størrelse grunnskole   | X          |              |         |               |
| Type videregående      |            | X            |         |               |
| Størrelse videregående |            | X            |         |               |
| Skolestørrelse         | X          | X            |         |               |
| Landsdel               | X          | X            | X       | X             |
| Fylke                  | X          | X            | X       |               |
| Kommunestørrelse       | X          | X            | X       |               |
| Sentralitetsindeks     | X          | X            | X       |               |

: Bakgrunnsvariabler for respondentgruppene {#tbl-tab2_1}

Vi koder svarstatus for respondentene i fem kategorier. Kategorien *godkjent* henviser her til de respondentene som har gjennomført hele undersøkelsen. *Godkjent -- noen svar* henviser til respondenter som ikke har fullført, men svart på minst 30 prosent av spørsmålene i sin gruppe. *Ikke godkjent -- noen svar* er dermed de respondentene som har svart på mindre enn 30 prosent. Disse tas ut av datamaterialet for å unngå at eksempelvis respondenter som kun klikker seg gjennom de første sidene uten å besvare undersøkelsen inkluderes, og for å unngå en kunstig høy svarprosent. Den nest siste kategorien består av dem som *ikke har svart*. Kategorien *frafalt* henviser til de respondentene som aktivt har gitt beskjed om at de ikke ønsker eller har anledning til å svare.

Populasjonstallene for grunnskoler, videregående skoler og kommuner er hentet fra Nasjonalt skoleregister (NSR).

Spørreskjemaet blir vanligvis utarbeidet i et samarbeid mellom Utdanningsdirektoratet og NIFU. Utdanningsdirektoratet utarbeider førsteutkast. NIFU kommer med forslag til endringer knyttet til *utformingen* av spørsmålene, men lar det i hovedsak være opp til oppdragsgiver selv å bestemme *innholdet* i disse. Spørsmålene blir også pilotert og gjennomgått av en referansegruppe bestående av representanter fra målgruppene.
