project:
  type: website
  output-dir: "_site"

## NB: Folder and file names are case-sensitive!

website:
  title: "Spørsmål til Skole-Norge"
  navbar:
    logo: "https://www.nifu.no/wp-content/uploads/logo_hvit.png"
    left:
      - file: "Main/om_historikk.qmd"
      - file: "Main/om_metode.qmd"
      - sidebar:Rapporter
      # - file: "main/tidligere_rapporter.qmd"
      # - sidebar:tidsserier
  sidebar:
    - id: Rapporter
      title: "Rapporter"
      contents: "Rapporter"
    # - id: tidsserier
    #   title: "Tidsserier"
    #   contents: "tidsserier"

execute:
  freeze: false
  cache: false

metadata-files:
  - _nifu_global.yaml # Must be in same folder/subfolder
